version: 0.2

phases:
  install:
    commands:
      - echo ==== tool versions ====
      - aws --version
      - docker --version
      - git --version
      - echo ==== environment variables ====
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION"
      - echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
      - echo "IMAGE_REPO_NAME=$IMAGE_REPO_NAME"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "GIT_URL=$GIT_URL"
      - echo "GIT_FETCH=$GIT_FETCH"
      - echo ==== info ====
      - pwd
      - whoami
      - echo ==== finished ====
  pre_build:
    commands:
      - echo ==== git clone repository ====
      - mkdir main || true
      - cd main
      -   git init || true
      -   git reset --hard HEAD || true
      -   git remote remove origin || true
      -   git remote add origin "$GIT_URL"
      -   git fetch origin "$GIT_FETCH"
      -   git checkout FETCH_HEAD
      - cd ..
      - echo ==== login to ECR ====
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - echo ==== login to DockerHub ====
      - |
        if test -n "$DOCKERHUB_USER"
        then
          echo "Docker Hub crendentials found."
          echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USER" --password-stdin
        else
          echo "Docker Hub crendentials not found."
        fi
      - echo ==== finished ====
  build:
    commands:
      - echo ==== build the Docker image ====
      - cd main
      -   docker build . -f ./docker/api/Dockerfile -t "$IMAGE_REPO_NAME:$IMAGE_TAG"
      -   docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - cd ..
      - echo ==== finished ====
  post_build:
    commands:
      - echo ==== push the Docker image ====
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo ==== output ====
      - cd main
      -   echo "!output=rev=$(git rev-parse HEAD)"
      - cd ..
      - echo "!output=imageSize=$(docker images "$IMAGE_REPO_NAME:$IMAGE_TAG" --format '{{ .Size }}')"
      - echo "!output=imageDigest=$(docker images "$IMAGE_REPO_NAME:$IMAGE_TAG" --no-trunc --format '{{ .ID }}')"
      - echo "!output=imageTag=$IMAGE_TAG"
      - echo "!output=imageRepoName=$IMAGE_REPO_NAME"
      - echo ==== finished ====

cache:
  paths:
    - "main/.git/**/*"
