version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.0.9"
    PNPM_VERSION: "6"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo ==== tool versions ====
      - aws --version
      - git --version
      - echo ==== install terraform ====
      - curl "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
      - unzip terraform.zip
      - install terraform /usr/local/bin
      - rm terraform.zip terraform
      - terraform -version
      - echo ==== install pnpm ====
      - npm i -g "pnpm@${PNPM_VERSION}"
      - pnpm --version
      - echo ==== info ====
      - pwd
      - whoami
      - echo ==== finished ====
  pre_build:
    commands:
      - echo ==== git clone main repository ====
      - mkdir main || true
      - cd main
      -   git init || true
      -   git reset --hard HEAD || true
      -   git remote remove origin || true
      -   git remote add origin "$GIT_URL_MAIN"
      -   git fetch origin "$GIT_FETCH_MAIN"
      -   git checkout FETCH_HEAD
      - cd ..
      - echo ==== git clone infra repository ====
      - mkdir infra || true
      - cd infra
      -   git init || true
      -   git reset --hard HEAD || true
      -   git remote remove origin || true
      -   git remote add origin "$GIT_URL_INFRA"
      -   git fetch origin "$GIT_FETCH_INFRA"
      -   git checkout FETCH_HEAD
      - cd
      - echo ==== infra/pnpm install ====
      - pnpm install --recursive --frozen-lockfile --prefer-offline
      - echo ==== finished ====
  build:
    commands:
      - echo ==== terraform apply ====
      - pnpm run --dir ./pkg/def deploy:env -- --auto-approve
      - echo ==== finished ====
  post_build:
    commands:
      - echo ==== TODO ====
      - echo ==== finished ====

cache:
  paths:
    - "main/.git/**/*"
    - "infra/.git/**/*"
    - "/root/.pnpm-store/**/*"
